// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderFlow.Infrastructure.Persistence.Configuration;

#nullable disable

namespace OrderFlow.Infrastructure.Persistence.Migrations.Accumulator
{
    [DbContext(typeof(AccumulatorDb))]
    [Migration("20260921130118_InitialAccumulator")]
    partial class InitialAccumulator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("accumulator")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderFlow.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClOrdId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("InputError")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey", "ClOrdId")
                        .IsUnique();

                    b.ToTable("Orders", "accumulator");
                });

            modelBuilder.Entity("OrderFlow.Domain.SymbolExposure", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Symbol");

                    b.ToTable("Exposures", "accumulator", t =>
                        {
                            t.HasCheckConstraint("CK_Exposure_Limit", "abs(\"Amount\") <= 100000000");
                        });

                    b.HasData(
                        new
                        {
                            Symbol = "PETR4",
                            Amount = 0m,
                            Version = 0L
                        },
                        new
                        {
                            Symbol = "VALE3",
                            Amount = 0m,
                            Version = 0L
                        },
                        new
                        {
                            Symbol = "VIIA4",
                            Amount = 0m,
                            Version = 0L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
