// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderFlow.Infrastructure.Persistence.Configuration;

#nullable disable

namespace OrderFlow.Infrastructure.Persistence.Migrations.Accumulator
{
    [DbContext(typeof(AccumulatorDb))]
    partial class AccumulatorDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("accumulator")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderFlow.Domain.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers", "accumulator");

                    b.HasData(
                        new
                        {
                            Id = "CLIENTE-001",
                            Name = "Cliente demonstração 1"
                        },
                        new
                        {
                            Id = "CLIENTE-002",
                            Name = "Cliente demonstração 2"
                        });
                });

            modelBuilder.Entity("OrderFlow.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("CLIENTE-001");

                    b.Property<string>("ClOrdId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputError")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionKey", "ClOrdId")
                        .IsUnique();

                    b.ToTable("Orders", "accumulator", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Side", "\"Side\" IN ('B', 'S')");
                        });
                });

            modelBuilder.Entity("OrderFlow.Domain.SymbolExposure", b =>
                {
                    b.Property<string>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("CLIENTE-001");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("DecisionSequence")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("AccountId", "Symbol");

                    b.ToTable("Exposures", "accumulator", t =>
                        {
                            t.HasCheckConstraint("CK_Exposure_Limit", "abs(\"Amount\") <= 100000000");
                        });

                    b.HasData(
                        new
                        {
                            AccountId = "CLIENTE-001",
                            Symbol = "PETR4",
                            Amount = 0m,
                            DecisionSequence = 0L,
                            Version = 0L
                        },
                        new
                        {
                            AccountId = "CLIENTE-001",
                            Symbol = "VALE3",
                            Amount = 0m,
                            DecisionSequence = 0L,
                            Version = 0L
                        },
                        new
                        {
                            AccountId = "CLIENTE-001",
                            Symbol = "VIIA4",
                            Amount = 0m,
                            DecisionSequence = 0L,
                            Version = 0L
                        },
                        new
                        {
                            AccountId = "CLIENTE-002",
                            Symbol = "PETR4",
                            Amount = 0m,
                            DecisionSequence = 0L,
                            Version = 0L
                        },
                        new
                        {
                            AccountId = "CLIENTE-002",
                            Symbol = "VALE3",
                            Amount = 0m,
                            DecisionSequence = 0L,
                            Version = 0L
                        },
                        new
                        {
                            AccountId = "CLIENTE-002",
                            Symbol = "VIIA4",
                            Amount = 0m,
                            DecisionSequence = 0L,
                            Version = 0L
                        });
                });

            modelBuilder.Entity("OrderFlow.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SymbolSequence")
                        .HasColumnType("bigint");

                    b.HasKey("EventId");

                    b.HasIndex("PartitionKey", "SymbolSequence")
                        .IsUnique();

                    b.HasIndex("PublishedAt", "NextAttemptAt");

                    b.ToTable("OutboxMessages", "accumulator");
                });

            modelBuilder.Entity("OrderFlow.Domain.SymbolExposure", b =>
                {
                    b.HasOne("OrderFlow.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
