// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderFlow.Infrastructure.Persistence;

#nullable disable

namespace OrderFlow.Infrastructure.Persistence.Migrations.Generator
{
    [DbContext(typeof(GeneratorDb))]
    [Migration("20260922001309_DurableFixAndAudit")]
    partial class DurableFixAndAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("generator")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderFlow.Infrastructure.Persistence.FixOutbox", b =>
                {
                    b.Property<string>("ClOrdId")
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClOrdId");

                    b.HasIndex("CompletedAt", "NextAttemptAt");

                    b.ToTable("FixOutbox", "generator");
                });

            modelBuilder.Entity("OrderFlow.Infrastructure.Persistence.InboxMessage", b =>
                {
                    b.Property<string>("Consumer")
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Consumer", "EventId");

                    b.ToTable("InboxMessages", "generator");
                });

            modelBuilder.Entity("OrderFlow.Infrastructure.Persistence.OrderEventProjection", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClOrdId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SymbolSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("ClOrdId", "OccurredAt");

                    b.ToTable("OrderEventProjections", "generator");
                });

            modelBuilder.Entity("OrderFlow.Infrastructure.Persistence.QuarantinedMessage", b =>
                {
                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<int>("Partition")
                        .HasColumnType("integer");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Topic", "Partition", "Offset");

                    b.ToTable("QuarantinedMessages", "generator");
                });

            modelBuilder.Entity("OrderFlow.Infrastructure.Persistence.Submission", b =>
                {
                    b.Property<string>("ClOrdId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClOrdId");

                    b.HasIndex("Status", "LastAttemptAt");

                    b.ToTable("Submissions", "generator");
                });

            modelBuilder.Entity("OrderFlow.Infrastructure.Persistence.FixOutbox", b =>
                {
                    b.HasOne("OrderFlow.Infrastructure.Persistence.Submission", null)
                        .WithOne()
                        .HasForeignKey("OrderFlow.Infrastructure.Persistence.FixOutbox", "ClOrdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
